name: Build firmware

on:
  pull_request:
  workflow_dispatch:

env:
  PROJECT: "electrowatch"

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prerequisites
      run: mv "parameters.h.example" "parameters.h"

    - uses: arduino/compile-sketches@v1
      with:
        fqbn: esp32:esp32:watchy:Revision=v20,PartitionScheme=huge_app,UploadSpeed=921600,DebugLevel=none
        platforms: |
          - name: esp32:esp32
            source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        sketch-paths: "${{ env.PROJECT }}.ino"
        libraries: |
          - name: Watchy
        enable-deltas-report: true
