name: Build firmware

on:
  pull_request:
  workflow_dispatch:

env:
  PROJECT: "electrowatch"

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prerequisites
      run: |
        mv "parameters.h.example" "parameters.h"
        brew install arduino-cli

    - name: Install lib and platform
      run: |
        arduino-cli core update-index --additional-urls \
          https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli core install esp32:esp32
        arduino-cli lib install Watchy

    - name: Run arduino-cli
      run: |
        arduino-cli compile "${{ env.PROJECT }}.ino" \
          --fqbn "esp32:esp32:watchy:Revision=v20,PartitionScheme=huge_app,UploadSpeed=921600,DebugLevel=none" \
          --log-level error

