name: Build firmware

on:
  pull_request:
  workflow_dispatch:

env:
  PROJECT: "electrowatch"

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prerequisites
      run: mv "${{ env.PROJECT }}/parameters.h.example" "${{ env.PROJECT }}/parameters.h"

    - uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp32:esp32:watchy:Revision=v20,PartitionScheme=huge_app,UploadSpeed=921600,DebugLevel=none
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: Watchy
        sketch-names-find-start: "${{ env.PROJECT }}/"
        sketch-names: "${{ env.PROJECT }}.ino"
