name: Build firmware

on:
  pull_request:
  workflow_dispatch:

env:
  PROJECT: "electrowatch"

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prerequisites
      run: mv "${{ env.PROJECT }}/parameters.h.example" "${{ env.PROJECT }}/parameters.h"

    - uses: arduino/compile-sketches@v1
      with:
        fqbn: esp32:esp32:esp32
        platforms: |
          - name: esp32:esp32
            source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        sketch-paths: "${{ env.PROJECT }}/${{ env.PROJECT }}.ino"
        libraries: |
          - name: Watchy
        cli-compile-flags: |
          - --build-property
          - build.partitions=huge_app
          - --build-property
          - upload.maximum_size=921600
        enable-deltas-report: true
