name: Build firmware

on:
  pull_request:
  workflow_dispatch:

env:
  PROJECT: "7_SEG"

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prerequisites
      run: mv "${{ env.IMAGE_NAME }}/settings.h.example ${{ env.IMAGE_NAME }}/settings.h"

    - uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp32:esp32:watchy:Revision=v20,PartitionScheme=min_spiffs,UploadSpeed=921600,DebugLevel=none,EraseFlash=none
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: Adafruit GFX Library,Arduino_JSON,DS3232RTC,NTPClient,Rtc_Pcf8563,GxEPD2,WiFiManager
        sketch-names-find-start: "${{ env.IMAGE_NAME }}/"
        sketch-names: "${{ env.IMAGE_NAME }}.ino"
