name: Styles check

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT: "7_SEG"

jobs:
  style:
    name: "C++ linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          step-summary: true
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
