name: Styles check

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT: "7_SEG"

jobs:
  style:
    name: "C++ linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          path: "${{ env.PROJECT }}/"
